name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # or your default branch name
      - feat-deploy

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: flask-app
  REGION: europe-west1  # Changed to EU West region
  REGISTRY: ghcr.io

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Container
      run: |
        cd backend
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ${{ env.REGISTRY }}/$REPO_OWNER/flask-app:${{ github.sha }} .
        docker push ${{ env.REGISTRY }}/$REPO_OWNER/flask-app:${{ github.sha }}

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        image: ${{ env.REGISTRY }}/$REPO_OWNER/flask-app:${{ github.sha }}
        region: ${{ env.REGION }}
        flags: '--platform managed --allow-unauthenticated' 